version: "2"
services:
  web:
    image: galgg/app_frontend:24.04.23
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:3001/shorten
      
  server:
    image: galgg/app_backend:24.04.23
    ports:
      - "3001:3001"
    environment:
      - SERVER_URL=http://127.0.0.1:3001
      - SERVER_PORT=3001
      - MONGODB_URL=mongodb://mongo:27017/urlShortener

  mongo:
    image: mongo
    ports:
      - "27017:27017"
      