apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-app
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:galg-gh/url-shortener.git
    path: ./deployment/helm/url-shortener/
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
