apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "url-shortener.fullname" . }}-ingress
  labels:
  {{- include "url-shortener.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "url-shortener.fullname" . }}-frontend'
            port:
              number: 80
        path: /
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "url-shortener.fullname" . }}-backend'
            port:
              number: 80
        path: /shorten
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "url-shortener.fullname" . }}-backend'
            port:
              number: 80
        path: /[A-Za-z0-9_-]{6}$
        pathType: ImplementationSpecific