apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "url-shortener.name" . }}-ingress
  labels:
  {{- include "url-shortener.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: '{{ include "url-shortener.name" . }}-web'
            port:
              number: {{ .Values.web.ports.servicePort }}
  - http:
      paths:
      - path: /static/
        pathType: Exact
        backend:
          service:
            name: '{{ include "url-shortener.name" . }}-web'
            port:
              number: 80
  - http:
      paths:
      - path: /shorten
        pathType: Exact
        backend:
          service:
            name: '{{ include "url-shortener.name" . }}-server'
            port:
              number: {{ .Values.server.ports.servicePort }}
  - http:
      paths:
      - path: /[A-Za-z0-9_-]{6}
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ include "url-shortener.name" . }}-server'
            port:
              number: {{ .Values.server.ports.servicePort }}
