apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.name" . }}-web
  labels:
  {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.type }}
  selector:
    app: {{ include "url-shortener.name" . }}-web
  ports:
  - port: {{ .Values.web.ports.servicePort }}
    targetPort: {{ .Values.web.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.name" . }}-server
  labels:
  {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  selector:
    app: {{ include "url-shortener.name" . }}-server
  ports:
  - port: {{ .Values.server.ports.servicePort }}
    targetPort: {{ .Values.server.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.name" . }}-db
  labels:
  {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.type }}
  selector:
    app: {{ include "url-shortener.name" . }}-db
  ports:
  - port: {{ .Values.db.ports.servicePort }}
    targetPort: {{ .Values.db.ports.containerPort }}