name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        tags: |
          type=raw,value={{date +%y.%m.%d}}

    - name: Login to Docker Hub 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: frontend/.
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_frontend:${{ steps.meta.outputs.tags }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: backend/.
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_backend:${{ steps.meta.outputs.tags }}
        
