name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./application/frontend/.
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_frontend:24.06.01

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./application/backend/.
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_backend:24.06.01
